// Import your CSS files
import './styles/font.css';      // Import the custom fonts
import './styles/variables.css'; // Import the CSS variables
import './styles/globals.css';   // Import the global styles

export const metadata = {
  title: 'Atharva Ranade',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
